version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env
      - nv.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    command: "export OC_PASS=Hallowelt123! && sudo -u www-data php /var/www/html/occ user:add --password-from-env --display-name='user' --group='users' user"
    pull_policy: build
    restart: always
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
      - nv.env
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
